baseURL = "https://www.ivpn.net"

[params]
    cdnUrl = "https://cdn.ivpn.net"
    environment = "production"     
    matomoEnabled = true
    matomoUrl = "https://stats.ivpn.net"
    matomoSiteId = 1